package fr.stein.maxbooker.domain.utils

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import fr.stein.maxbooker.R

object StringUtils {
    @Composable
    fun getScreenBookDetailSeatString(seatString: String): String = when (seatString) {
        "AACC" -> stringResource(R.string.screen_book_detail_seat_AACC)
        "ACAL" -> stringResource(R.string.screen_book_detail_seat_ACAL)
        "ACAR" -> stringResource(R.string.screen_book_detail_seat_ACAR)
        "ACDO" -> stringResource(R.string.screen_book_detail_seat_ACDO)
        "ACEN" -> stringResource(R.string.screen_book_detail_seat_ACEN)
        "ACMP" -> stringResource(R.string.screen_book_detail_seat_ACMP)
        "ACOU" -> stringResource(R.string.screen_book_detail_seat_ACOU)
        "ACQT" -> stringResource(R.string.screen_book_detail_seat_ACQT)
        "ADOC" -> stringResource(R.string.screen_book_detail_seat_ADOC)
        "AEEC" -> stringResource(R.string.screen_book_detail_seat_AEEC)
        "AEQT" -> stringResource(R.string.screen_book_detail_seat_AEQT)
        "AFEN" -> stringResource(R.string.screen_book_detail_seat_AFEN)
        "AFIS" -> stringResource(R.string.screen_book_detail_seat_AFIS)
        "AHAN" -> stringResource(R.string.screen_book_detail_seat_AHAN)
        "AHDC" -> stringResource(R.string.screen_book_detail_seat_AHDC)
        "AINC" -> stringResource(R.string.screen_book_detail_seat_AINC)
        "AKID" -> stringResource(R.string.screen_book_detail_seat_AKID)
        "AKSK" -> stringResource(R.string.screen_book_detail_seat_AKSK)
        "AMIL" -> stringResource(R.string.screen_book_detail_seat_AMIL)
        "AMOM" -> stringResource(R.string.screen_book_detail_seat_AMOM)
        "ANBI" -> stringResource(R.string.screen_book_detail_seat_ANBI)
        "ANHI" -> stringResource(R.string.screen_book_detail_seat_ANHI)
        "ANUR" -> stringResource(R.string.screen_book_detail_seat_ANUR)
        "ANVB" -> stringResource(R.string.screen_book_detail_seat_ANVB)
        "ANVH" -> stringResource(R.string.screen_book_detail_seat_ANVH)
        "APAN" -> stringResource(R.string.screen_book_detail_seat_APAN)
        "ASDM" -> stringResource(R.string.screen_book_detail_seat_ASDM)
        "ASII" -> stringResource(R.string.screen_book_detail_seat_ASII)
        "ASIL" -> stringResource(R.string.screen_book_detail_seat_ASIL)
        "ASLL" -> stringResource(R.string.screen_book_detail_seat_ASLL)
        "ASLO" -> stringResource(R.string.screen_book_detail_seat_ASLO)
        "ATAB" -> stringResource(R.string.screen_book_detail_seat_ATAB)
        "ATEL" -> stringResource(R.string.screen_book_detail_seat_ATEL)
        "CBAS" -> stringResource(R.string.screen_book_detail_seat_CBAS)
        "CDAS" -> stringResource(R.string.screen_book_detail_seat_CDAS)
        "CHAU" -> stringResource(R.string.screen_book_detail_seat_CHAU)
        "CIRE" -> stringResource(R.string.screen_book_detail_seat_CIRE)
        "CMIL" -> stringResource(R.string.screen_book_detail_seat_CMIL)
        "LBAS" -> stringResource(R.string.screen_book_detail_seat_LBAS)
        "LHAU" -> stringResource(R.string.screen_book_detail_seat_LHAU)
        "LMIL" -> stringResource(R.string.screen_book_detail_seat_LMIL)
        "VCFA" -> stringResource(R.string.screen_book_detail_seat_VCFA)
        "VCFE" -> stringResource(R.string.screen_book_detail_seat_VCFE)
        "VCHO" -> stringResource(R.string.screen_book_detail_seat_VCHO)
        "CPRI" -> stringResource(R.string.screen_book_detail_seat_CPRI)
        "CFAM" -> stringResource(R.string.screen_book_detail_seat_CFAM)
        "AVEP" -> stringResource(R.string.screen_book_detail_seat_AVEP)
        "CVEP" -> stringResource(R.string.screen_book_detail_seat_CVEP)
        "LVEP" -> stringResource(R.string.screen_book_detail_seat_LVEP)
        "AVGL" -> stringResource(R.string.screen_book_detail_seat_AVGL)
        "APAF" -> stringResource(R.string.screen_book_detail_seat_APAF)
        "ATEI" -> stringResource(R.string.screen_book_detail_seat_ATEI)
        "AVEG" -> stringResource(R.string.screen_book_detail_seat_AVEG)
        "AFAM" -> stringResource(R.string.screen_book_detail_seat_AFAM)
        else -> stringResource(R.string.screen_book_detail_seat_unknown)
    }
}
