[versions]
agp = "9.2.1"
kotlin = "2.3.20"
coreKtx = "1.18.0"
ksp = "2.3.2"
ktlint = "14.2.0"
google-services = "4.4.4"
firebase-bom = "34.11.0"
firebase-perf = "2.0.2"
protobuf = "0.9.6"
protobuf-javalite = "4.26.1" # Using outdated version (see https://github.com/firebase/firebase-android-sdk/issues/5997)
hilt = "2.59.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
composeBom = "2026.03.01"
androidx-hilt-navigation-compose = "1.3.0"
androidx-hilt-compiler = "1.3.0"
androidx-hilt-work = "1.3.0"
androidx-compose-material-icons = "1.7.8"
androidx-compose-material-extended = "1.7.8"
androidx-material3 = "1.4.0"
androidx-navigation-compose = "2.9.7"
androidx-material3-adaptive = "1.2.0"
androidx-material3-adaptive-layout = "1.2.0"
androidx-material3-adaptive-navigation = "1.2.0"
androidx-material3-adaptive-navigation-suite = "1.4.0"
androidx-datastore = "1.2.1"
androidx-room = "2.8.4"
androidx-work = "2.11.2"
retrofit = "3.0.0"
jackson-kotlin = "2.21.2"
jackson-datatype-jsr310 = "2.21.2"
lottie-compose = "6.7.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom"}
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics"}
firebase-perf = { group = "com.google.firebase", name = "firebase-perf"}
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf-javalite" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref= "androidx-compose-material-icons"}
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref= "androidx-compose-material-extended"}
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt-compiler" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt-work" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-material3" }
androidx-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "androidx-material3-adaptive" }
androidx-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "androidx-material3-adaptive-layout" }
androidx-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "androidx-material3-adaptive-navigation" }
androidx-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "androidx-material3-adaptive-navigation-suite" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }
jackson = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson-kotlin" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson-datatype-jsr310" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-jackson = { group = "com.squareup.retrofit2", name = "converter-jackson", version.ref = "retrofit"}
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie-compose"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services"}
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-perf"}